[tools]
go = "latest"
node = "latest"
npm = "latest"
python = "latest"
rust = "latest"
neovim = "nightly"
ripgrep = "latest"
lsd = "latest"
bat = "latest"
fzf = "latest"
fd = "latest"
# chezmoi = "latest"
usage = "latest"
tmux = "latest"
github-cli = "latest"
java = "temurin-17"
zig = "latest"
maven = "3.9"

[settings]
idiomatic_version_file_enable_tools = ["node", "go"]
