[tools]
go = "latest"
node = "latest"
npm = "latest"
python = "latest"
rust = "latest"
neovim = "latest"
ripgrep = "latest"
lsd = "latest"
bat = "latest"
fzf = "latest"
fd = "latest"
# chezmoi = "latest"
usage = "latest" # for mise completion
tmux = "latest"
github-cli = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
