[tools]
go = "latest"
node = "latest"
npm = "latest"
python = ["latest", "3.13"]
rust = "latest"
neovim = "nightly"
ripgrep = "latest"
lsd = "latest"
bat = "latest"
fzf = "latest"
fd = "latest"
usage = "latest"
tmux = "latest"
github-cli = "latest"
java = "temurin-17"
zig = "latest"
maven = "3.9"
chezmoi = "latest"
uv = "latest"
"npm:@nestjs/cli" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "go"]
